# Generated by Django 4.0.3 on 2022-04-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PmjoStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipcode',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
