# Generated by Django 4.0.3 on 2022-04-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PmjoStore', '0002_alter_zipcode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipcode',
            options={},
        ),
    ]
