# Generated by Django 3.2.7 on 2022-04-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PmjoStore', '0003_alter_zipcode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeemployees',
            options={'verbose_name_plural': 'Store Employees'},
        ),
        migrations.AddField(
            model_name='storeemployees',
            name='store_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='PmjoStore.store'),
        ),
    ]
