# Generated by Django 3.2.7 on 2022-04-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PmjoStore', '0005_auto_20220409_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='zipCode_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='PmjoStore.zipcode'),
        ),
    ]
