# Generated by Django 3.2.7 on 2022-04-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PmjoStore', '0008_auto_20220410_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='bike_prod_id',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='PmjoStore.bikeproducts'),
        ),
    ]
