# Generated by Django 4.0.3 on 2022-03-19 22:17

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_store_email_alter_store_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='state',
            field=localflavor.us.models.USStateField(default='PA', max_length=2),
        ),
    ]
