# Generated by Django 4.0.3 on 2022-03-20 00:23

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_store_street_alter_store_city_alter_store_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('store_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('store_id', models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreEmployees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('store_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
