# Generated by Django 4.0.3 on 2022-03-20 00:58

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_managers_staff_stocklist_storeemployees_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', localflavor.us.models.USStateField(default='PA', max_length=2)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='managers',
            name='staff_id',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.staff'),
        ),
        migrations.AddField(
            model_name='storeemployees',
            name='staff_id',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.staff'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='store_id',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.store'),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeemployees',
            name='store_id',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.store'),
        ),
    ]
