# Generated by Django 4.0.3 on 2022-03-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_customers_managers_staff_id_storeemployees_staff_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklist',
            name='store_id',
        ),
        migrations.AddField(
            model_name='stocklist',
            name='store_id',
            field=models.ManyToManyField(blank=True, default=1, to='Products.store'),
        ),
    ]
