# Generated by Django 4.0.3 on 2022-03-20 01:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_remove_stocklist_store_id_stocklist_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBrands',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(choices=[('giant_bikes', 'Giant Bikes'), ('trek_bikes', 'Trek Bikes'), ('specialized', 'Specialized'), ('santa_cruz', 'Santa Cruz'), ('gt', 'GT'), ('yeti', 'Yeti'), ('cannondale', 'Cannondale'), ('marin', 'Marin'), ('diamondback', 'DiamondBack')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('mountain_bike', 'Mountain Bike'), ('road_bike', 'Road Bike'), ('touring_bike', 'Touring Bike'), ('folding_bike', 'Folding Bike'), ('track_bike', 'Track Bike'), ('cruiser', 'Cruiser'), ('bmx', 'BMX'), ('recumbent', 'Recumbent'), ('utility', 'Utility'), ('trike', 'Trike')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stocklist',
            name='store_id',
        ),
        migrations.AddField(
            model_name='stocklist',
            name='store_id',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.store'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('cust_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.customers')),
                ('store_staff_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.storeemployees')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikeProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('price', models.PositiveIntegerField(default=0)),
                ('bike_brand_id', models.ManyToManyField(to='Products.bikebrands')),
                ('bike_cat_id', models.ManyToManyField(to='Products.bikecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
