# Generated by Django 4.0.3 on 2022-03-20 01:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_bikebrands_bikecategory_remove_stocklist_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('bike_prod_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.bikeproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='item_id',
            field=models.ManyToManyField(blank=True, to='Products.cartitems'),
        ),
    ]
