# Generated by Django 4.0.3 on 2022-03-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_cartitems_orders_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikebrands',
            options={'verbose_name_plural': 'Bike Brands'},
        ),
        migrations.AlterModelOptions(
            name='bikecategory',
            options={'verbose_name_plural': 'Bike Categories'},
        ),
        migrations.AlterModelOptions(
            name='bikeproducts',
            options={'verbose_name_plural': 'Bike Products'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='stocklist',
            name='bike_prod_id',
            field=models.ManyToManyField(to='Products.bikeproducts'),
        ),
    ]
