# Generated by Django 4.0.3 on 2022-03-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_storeemployees_options_remove_store_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikecategory',
            name='category',
            field=models.CharField(choices=[('mountain_bike', 'Mountain Bike'), ('road_bike', 'Road Bike'), ('touring_bike', 'Touring Bike'), ('folding_bike', 'Folding Bike'), ('track_bike', 'Track Bike'), ('cruiser', 'Cruiser'), ('bmx', 'BMX'), ('recumbent', 'Recumbent'), ('utility', 'Utility'), ('trike', 'Trike')], max_length=100, unique=True),
        ),
    ]
