# Generated by Django 4.0.3 on 2022-03-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_bikecategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeproducts',
            name='bike_brand_id',
        ),
        migrations.AddField(
            model_name='bikeproducts',
            name='bike_brand_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.bikebrands'),
        ),
        migrations.RemoveField(
            model_name='bikeproducts',
            name='bike_cat_id',
        ),
        migrations.AddField(
            model_name='bikeproducts',
            name='bike_cat_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.bikecategory'),
        ),
    ]
