# Generated by Django 4.0.3 on 2022-03-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_remove_bikeproducts_bike_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikebrands',
            name='brand',
            field=models.CharField(choices=[('giant_bikes', 'Giant Bikes'), ('trek_bikes', 'Trek Bikes'), ('specialized', 'Specialized'), ('santa_cruz', 'Santa Cruz'), ('gt', 'GT'), ('yeti', 'Yeti'), ('cannondale', 'Cannondale'), ('marin', 'Marin'), ('diamondback', 'DiamondBack')], max_length=100, unique=True),
        ),
    ]
