# Generated by Django 4.0.3 on 2022-03-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_bikebrands_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeemployees',
            name='store_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.store'),
        ),
    ]
