# Generated by Django 4.0.3 on 2022-03-20 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_alter_storeemployees_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_id',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='order_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.orders'),
        ),
    ]
