# Generated by Django 4.0.3 on 2022-03-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_remove_orders_item_id_cartitems_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='order_id',
        ),
    ]
